### PR TITLE
Fix inactive GSK versions breaking commands for existing clusters

### LINKED ISSUE #461: Inactive GSK versions break terraform commands for existing clusters
### Precondition

You need a cluster which was set up on a version that is not active anymore.
As example, a cluster using `1.31.9-gs0` would work because that version was deactivated approx. one month ago. The latest version would be `1.31.11-gs0`

```
resource "gridscale_k8s" "gsk-test" {
  name   = "gsk-test"
  gsk_version = "1.31.9-gs0"

  node_pool {
    name = "pool-0"
    node_count = 1
    cores = 2
    memory = 4
    storage = 30
    storage_type = "storage_insane"
  }
}
```

### Steps

With such an existing cluster, you simply need to run an operation like `terraform plan` and you will get an error:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: 1.31.9-gs0 is a deprecated gridscale Kubernetes (GSK) version. Valid GSK versions are: ...
│
│   with module.mgmt_cluster.gridscale_k8s.cluster,
│   on cluster.tf line 3, in resource "gridscale_k8s" "gsk-test":
│    3: resource "gridscale_k8s" "gsk-test" {
│
╵
```

You don't even need to change any parameters like the `node_pool`.

## Expected

I can run `terraform plan` and `terraform apply` on a cluster, whose version is not active anymore. I should still be able to update my state or change the clusters configuration.

## Actual

Running those operations is not possible.

Thus I can not change my cluster configuration via Terraform.

## Root Cause

The logic introduced in #413 did not take into account the existance of old clusters.

## Solution

We need to refactor this function:

https://github.com/gridscale/terraform-provider-gridscale/blob/f467c3e3ad120b625089ffd87f9efc850232f964/gridscale/resource_gridscale_k8s.go#L483

### Technical Requirements

- We should still check if a template is active or not. But doing so is not the responsibility of the `deriveK8sTemplateFromGSKVersion` function and instead the parent functions calling it. There we can differentiate between:
  - It should not be allowed to create a cluster on a disabled template
  - It should not be allowed to ugprade from some **different** version to a disabled template.
  - It should be allowed to run an update on a disabled version, if it is not an upgrade. This allows to change pool or other params without upgrading the cluster.

### PR DESCRIPTION
**Pull request by fabiante**
This PR aims to fix #461 

## Manual testing

Testing this fix is complex. Locally i have used the following approach.

1. Create a real cluster using this version

```
resource "gridscale_k8s" "gsk-test" {
  name   = "gsk-test"
  gsk_version = "1.30.14-gs0" # active - this was the version used to create this cluster
  # gsk_version = "1.31.9-gs0" # inactive
  # gsk_version = "1.31.11-gs0" # active

  node_pool {
    name = "pool-0"
    node_count = 1
    cores = 2
    memory = 4
    storage = 30
    storage_type = "storage_insane"
  }

  timeouts {
    create = "60m"
    update = "60m"
    delete = "60m"
  }
}
```

2. After creation, add this mocking to the source code and build the provider. Follow the README for using your local build

```diff
--- a/vendor/github.com/gridscale/gsclient-go/v3/paas.go
+++ b/vendor/github.com/gridscale/gsclient-go/v3/paas.go
@@ -610,6 +610,12 @@ func (c *Client) GetPaaSTemplateList(ctx context.Context) ([]PaaSTemplate, error
                paasTemplate := PaaSTemplate{
                        Properties: properties,
                }
+
+               // Mock disabled templates
+               if paasTemplate.Properties.Version == "1.30.14-gs0" { // This is the version the cluster was created with.
+                       paasTemplate.Properties.Active = false
+               }
+
                paasTemplates = append(paasTemplates, paasTemplate)
        }
        return paasTemplates, err
```

What this does is it fakes that the version you just used to provision the cluster is inactive.

3. Run `terraform plan` with the various `gsk_version` values from above. You should:
  - run it without any changes
  - run it with an upgraded, active version
  - run it with an upgraded, inactive version (this is the only thing that should fail)

### CODE REVIEW

**Comment by fabiante** [comment]
I have just now pushed a simpler approach to fixing this.

I would have liked to pull up the whole validation logic into the parent functions, but I failed to properly do that.

This new push contains a simpler version which we can still refactor moving forward.

File: gridscale/resource_gridscale_k8s.go [hunk 1]
```diff
@@ -542,22 +556,28 @@ func deriveK8sTemplateFromRelease(client *gsclient.Client, release, currenTempla
...
+				break
 			}
 		}
 	}
 	if !derived {
 		return nil, fmt.Errorf("%v is an invalid Kubernetes release. Valid releases are: %v", release, strings.Join(releases, ", "))
 	}
+	if checkActive && !isActive {
+		return nil, fmt.Errorf("%v is a deprecated gridscale Kubernetes (GSK) release. Valid GSK releases are: %v", version, strings.Join(releases, ", "))
+	}
```
Comment (fabiante) [inline gridscale/resource_gridscale_k8s.go:590]: @nvthongswansea This function, compared to `deriveK8sTemplateFromGSKVersion` was structured a bit differend with regards to the `active` flag.

I have now made them pretty much the same and think that is the correct behavior.

Please review this change thoroughly.

Comment (fabiante) [reply gridscale/resource_gridscale_k8s.go:590]: @nvthongswansea In your initial draft you had this:

```
	for _, paasTemplate := range paasTemplates {
		if paasTemplate.Properties.Flavour == k8sTemplateFlavourName && paasTemplate.Properties.Active && checkActive {
			releases = append(releases, paasTemplate.Properties.Release)

			if paasTemplate.Properties.Release == release {
				derived = true
				template = paasTemplate
			}
		}
	}
``` 

Here the template would not have matched (okay) but also the template would not have been added to the `releases` slice. But we want that, to display the proper error message later.

That is also why I changed this implementation a bit.

**Review by nvthongswansea — APPROVED** [review]
LGTM. Please merge after testing.

Edit: and after resolving the thread above.

File: gridscale/resource_gridscale_k8s.go (hunk 1 above)
Comment (nvthongswansea) [reply gridscale/resource_gridscale_k8s.go:590]: @fabiante with the `break`, the list of valid `release` might miss some releases.

Comment (fabiante) [reply gridscale/resource_gridscale_k8s.go:590]: Oh right. Will fix that.

Comment (fabiante) [reply gridscale/resource_gridscale_k8s.go:590]: Wait a minute, that problem also exists for `deriveK8sTemplateFromGSKVersion` - what do you think, should i fix the logic for both so that both of them will properly collect all versions/releases?

Comment (fabiante) [reply gridscale/resource_gridscale_k8s.go:590]: I have decided to do it as described above.
